USE [master]
GO
/****** Object:  Database [Cgroup99]    Script Date: 23/01/2023 00:54:55 ******/
CREATE DATABASE [Cgroup99]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cgroup99', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Cgroup99.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cgroup99_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Cgroup99_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Cgroup99] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cgroup99].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Cgroup99] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Cgroup99] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Cgroup99] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Cgroup99] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Cgroup99] SET ARITHABORT OFF 
GO
ALTER DATABASE [Cgroup99] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Cgroup99] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Cgroup99] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Cgroup99] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Cgroup99] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Cgroup99] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Cgroup99] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Cgroup99] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Cgroup99] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Cgroup99] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Cgroup99] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Cgroup99] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Cgroup99] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Cgroup99] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Cgroup99] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Cgroup99] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Cgroup99] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Cgroup99] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Cgroup99] SET  MULTI_USER 
GO
ALTER DATABASE [Cgroup99] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Cgroup99] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Cgroup99] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Cgroup99] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Cgroup99] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Cgroup99] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Cgroup99] SET QUERY_STORE = OFF
GO
USE [Cgroup99]
GO
/****** Object:  Table [dbo].[Ingredient]    Script Date: 23/01/2023 00:54:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredient](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[image] [nvarchar](1000) NOT NULL,
	[calories] [int] NOT NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ingredientsInRecipes]    Script Date: 23/01/2023 00:54:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ingredientsInRecipes](
	[recipeId] [int] NOT NULL,
	[ingredientId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[recipeId] ASC,
	[ingredientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipes]    Script Date: 23/01/2023 00:54:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipes](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[image] [nvarchar](1000) NOT NULL,
	[cookingMethod] [nvarchar](50) NOT NULL,
	[time] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ingredientsInRecipes]  WITH CHECK ADD FOREIGN KEY([ingredientId])
REFERENCES [dbo].[Ingredient] ([id])
GO
ALTER TABLE [dbo].[ingredientsInRecipes]  WITH CHECK ADD FOREIGN KEY([recipeId])
REFERENCES [dbo].[Recipes] ([id])
GO
USE [master]
GO
ALTER DATABASE [Cgroup99] SET  READ_WRITE 
GO
